name: Build and Deploy Playground

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: playground
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python '3.12'
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: 'pip'
    - name: Setup Python venv
      run: |
        make setup
    - name: Build the JupyterLite site
      run: |
        make build-playground
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./playground/dist

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
